"use client";
import { useState } from "react";

const VerifyUser = ({
  username,
  onUsernameChange,
  selectedTickets = [],
  memo, // Memo generated by NumberRoller
  onUserVerified = () => {},
}) => {
  const [message, setMessage] = useState("");
  const [loading, setLoading] = useState(false);

  const handleVerify = async () => {
    if (!username.trim()) {
      setMessage("❌ Please enter a valid Steemit username.");
      return;
    }
    if (selectedTickets.length === 0 || !memo) {
      setMessage("❌ Ticket details are missing. Please complete ticket selection.");
      return;
    }
    setLoading(true);
    setMessage("");

    try {
      // Combine data from VerifyUser (username) and NumberRoller (selectedTickets and memo)
      const ticketsBought = selectedTickets.length;
      const ticketNumbers = selectedTickets.join(", ");
      const payload = {
        username: username.replace(/^@/, "").toLowerCase(),
        tickets: selectedTickets,
        ticketsBought, // Number of tickets
        ticketNumbers, // Comma-separated ticket numbers
        memo,          // Memo generated from NumberRoller
        timestamp: new Date().toISOString(),
        isValid: false // Initially false; will display as grey until validated
      };

      // Send the combined data to Firebase via /api/storeTicket
      const storeResponse = await fetch("/api/storeTicket", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload),
      });
      const storeResult = await storeResponse.json();
      if (storeResult.success) {
        setMessage(`✅ Thank you @${username} for purchasing tickets. Your entry is recorded.`);
        onUserVerified(payload);
      } else {
        setMessage("❌ Failed to store your entry. Please try again.");
      }
    } catch (error) {
      console.error("Error during verification:", error);
      setMessage("⚠️ Error storing your entry. Please try again later.");
    }
    setLoading(false);
  };

  return (
    <div className="container mx-auto p-4 text-center">
      <h2 className="text-xl font-bold mb-4">🔍 Verify Your Lottery Entry</h2>
      <input
        type="text"
        value={username}
        onChange={(e) => onUsernameChange(e.target.value)}
        placeholder="Enter your Steemit username"
        className="border p-2 rounded w-64 text-center"
      />
      <button
        onClick={handleVerify}
        className="ml-2 bg-green-500 text-white px-4 py-2 rounded hover:bg-green-600"
        disabled={loading}
      >
        {loading ? "Processing..." : "Verify Entry"}
      </button>
      {message && <p className="mt-4 text-lg">{message}</p>}
      <p className="mt-2 text-sm text-gray-600">
        Note: Very recent transactions might take up to 30 seconds to appear.
      </p>
    </div>
  );
};

export default VerifyUser;
